services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # bind on all interfaces
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092

      # advertise for in-Docker clients and for anyone hitting localhost:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./l1_day.csv:/app/l1_day.csv:ro
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    # wait for Kafka, run producer, then stay alive
    command: sh -c "sleep 10 && python kafka_producer.py"

  backtester:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./l1_day.csv:/app/l1_day.csv:ro
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    # wait for Kafka, run backtest, then stay alive
    command: sh -c "sleep 10 && python backtest.py"
